# Find the Dockerfile for mcr.microsoft.com/azure-functions/powershell:4.0-powershell${VARIANT}-core-tools at this URL
# https://github.com/Azure/azure-functions-docker/tree/dev/host/4/bullseye/amd64/powershell

# Update the VARIANT arg in devcontainer.json to pick a supported PowerShell version: 7.0, 7.2
ARG VARIANT=7.2
FROM mcr.microsoft.com/azure-functions/powershell:4-powershell${VARIANT}-core-tools
